# Generated by Django 4.2 on 2023-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sequence',
            field=models.FloatField(default=0),
        ),
    ]
