# Generated by Django 4.2 on 2023-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_image_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='sequence',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
