# Generated by Django 4.2 on 2023-04-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_image_id_alter_image_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asfeaturedon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
