# Generated by Django 4.2 on 2023-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_headings_delete_asfeaturedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='buttonText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_txt', models.CharField(max_length=15)),
            ],
        ),
    ]
