# Generated by Django 4.2 on 2023-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_buttontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttontext',
            name='btn_txt',
            field=models.CharField(max_length=50),
        ),
    ]
