# Generated by Django 4.2 on 2023-05-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_navitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='spareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolImage', models.ImageField(upload_to='media')),
                ('toolTitle', models.CharField(max_length=30)),
                ('toolPrice', models.FloatField()),
            ],
        ),
    ]
